### ISSUE TITLE
Investigate supporting ruby 1.9.3

### ISSUE THREAD

**Issue by orta** [CocoaPods/Cork#11]
The [default travis](https://docs.travis-ci.com/user/languages/ruby) is 1.9.3

> If you don’t specify a version, Travis CI will use MRI 1.9.3 as the default.

I wonder if we can support it, so that Danger can run fine on 1.9.3.

**Comment by segiddins** [comment]
👎 
Ruby 1.9.3 was EOL'ed several years ago -- even 2.0.0 is EOL at this point. Adding support for unsupported ruby versions when not totally necessary should be avoided.

**Comment by orta** [comment]
Yeah, that's fair. 👍
