### ISSUE TITLE
Integrate back into CocoaPods

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/Cork#3]
- [x] Create a CHANGELOG (saying this version is just extracted from CocoaPods).
- [x] Add `Cork` to Rainforest: https://github.com/CocoaPods/Rainforest/blob/master/Rakefile#L20 (via pull request)
- [x] Create a [pull request](https://github.com/CocoaPods/CocoaPods/issues/4784) into CocoaPods to add the gem
  - [x] Add to `cork` to [gemspec](https://github.com/CocoaPods/CocoaPods/blob/master/cocoapods.gemspec#L37) then bundle install
  - [x] Make `Pod::UI` be a subclass of `Cork::Board`
    - [x] Remove redundant code
    - [x] Remove redundant specs
    - [x] Override board configuration methods to call into `Pod::Config::Instance`

**Comment by KrauseFx** [comment]
for @Karla-Isabel-Sandoval
- [ ] Make `Pod::UI` be a subclass of `Cork::Board` (one is a `Module`, one is a `Class`, we have to decide for one)
  - [ ] Remove redundant code (We removed all the redundant code, once this can actually run, we can add missing methods to either `cork` or CocoaPods depending on where it belongs)
  - [ ] Remove redundant specs
  - [ ] Override board configuration methods to call into `Pod::Config::Instance`
